trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    contents: |
      dist/mongo-dbangular13/**
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: 'Copy files to artifact staging directory'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(build.artifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish build artifacts'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pwd 
      ls

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'appservice'
    appType: 'webAppLinux'
    WebAppName: 'nodes1122'
    packageForLinux: '$(build.artifactStagingDirectory)/*.zip'
    RuntimeStack: 'NODE|18-lts'
    StartupCommand: 'cd dist/mongo-dbangular13 && npm start'
  displayName: 'Deploy to Azure WebApp'
